/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InterfaceExample;

import javafx.application.Application;
import javafx.event.EventHandler;
import javafx.scene.Group;
import javafx.scene.Scene;
import javafx.scene.input.MouseEvent;
import javafx.scene.paint.Color;
import javafx.scene.shape.Rectangle;
import javafx.stage.Stage;

class Square extends Rectangle{

    @FunctionalInterface
    public interface onSquareClicked{
        void onClicked(int i, int j);
    }

    onSquareClicked mListener;

    int i = 0,j = 0;

    boolean mChecked = false;


    public void setOnSquareClickedListener(onSquareClicked listener){
        mListener = listener;
    }

    Square(double dimension, boolean checked){

        setWidth(dimension);
        setHeight(dimension);

        setStrokeWidth(0.5);
        setStroke(Color.BLACK);

        mChecked = checked;

        if(mChecked)
            setFill(Color.CADETBLUE);
        else
            setFill(Color.BEIGE);

        setOnMouseClicked(event->{
            System.out.println("["+i+", "+j+"]");

            switchChecked();

            if(mListener!=null){
                mListener.onClicked(i,j);
            }

        });
    }

    public void setCoordinates(int i, int j){
        this.i = i;
        this.j = j;
    }

    public void switchChecked(){
        mChecked=!mChecked;

        if(mChecked)
            setFill(Color.CADETBLUE);
        else
            setFill(Color.BEIGE);
    }
}

public class elo extends Application {
    int[] mData = new int[]{1,0,1,0,0,0,0,1};
    Square[] mGameboard = new Square[8];

    @Override
    public void start(Stage primaryStage) throws Exception {

        Group group = new Group();

        createGameboard();

        for(Square square : mGameboard)
            group.getChildren().add(square);


        Scene scene = new Scene(group,800,800);

        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public void createGameboard(){

        for(int no=0;no<mData.length;no++){

            Square square;

            if(mData[no]==1)
                square = new Square(100,true);
            else
                square = new Square(100,false);

            square.setTranslateX(100*no);
            square.setCoordinates(no,0);

            square.setOnSquareClickedListener((int i, int j)-> {

                System.out.println("kliknięto: "+i);


            });

            mGameboard[no] = square;

        }
    }

}